# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8771294e66703e3b16deb8a576da4abc52a28455b05af87b2b1ea513b83c4bcbb358a9b8ddeb20a086f75caefd0150b084b7efdf554a07d7223954860063424a

test:
  secret_key_base: f0ffe52cf61b6b40c66118d7414e09778a7cb72cf9f9ce996b30e2eb0f95ac5d4aa34cb4198daabd2c5b507ed46a1a1b6aaefbfa718a4122156f8039abb9dc82

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
